# Setup
title:        Gualtiero Testa
tagline:      The Art of Coding: experiences from software development world
url:          https://gualtierotesta.github.io
timezone:     Europe/Rome

# About/contact
author:
  name:              Gualtiero Testa
  url:               http://www.gualtierotesta.it
  email:             gualtiero.testa@gmail.com
