# Jekyll! configuration file

lsi: false
markdown: kramdown
highlighter: rouge
permalink: /:title
category_dir: topics
category_title_prefix:
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp"]
timezone: Europe/Rome
encoding: utf-8
theme: minima
plugins:
  - jekyll-feed


# Site settings
author: Gualtiero Testa
title: Gualtiero Testa personal blog
email: gualtiero.testa@gmail.com
description: "The Art of Coding: experiences from software development world"
twitter_username: gualtierotesta
github_username:  gualtierotesta
codewars_username: gualty